output_dir: aardwolf

script:
  - rm -rf ${OUTPUT_DIR}/*
  - make clean
  - make CC=clang CFLAGS='-g -O0 -Xclang -load -Xclang ${AARDWOLF_DIR}/libAardwolfLLVM.so' LDFLAGS=${AARDWOLF_DIR}/libaardwolf_runtime.a
  - AARDWOLF_EXTERNAL=${AARDWOLF_DIR}/aardwolf_external make test > ${RESULT_FILE}

plugins:
  - sbfl
  - prob-graph
