output_dir: .aardwolf

script:
  # Just run pytest (all the machinery is done in test modules)
  - pytest

plugins:
  - sbfl: sbfl-dstar
    options:
      n_results: 20
  - sbfl: sbfl-ochai
    options:
      metric: ochiai
  - sbfl: sbfl-tarantula
    options:
      metric: tarantula
