output_dir: bin

script:
  # Do all the stuff inside output directory
  - cd ${OUTPUT_DIR}
  # Analyse, instrument and compile sources
  - clang -Xclang -load -Xclang ${FRONTEND} -c -g -o ${TARGET_FILE}.o ../src/maintenance.c
  # Compile test runner and link it with the compiled source
  - clang -o ${EXEC_FILE} ../tests/test.c ${TARGET_FILE}.o ${RUNTIME_LIB}
  # Execute the test runner
  - ${EXEC_FILE} > ${RESULT_FILE}
  # Temporary solution for limited static data collection
  - mv maintenance.c.aard ${ANALYSIS_FILE}

plugins:
  - sbfl: sbfl-dstar
    options:
      n_results: 20
  - sbfl: sbfl-ochai
    options:
      metric: ochiai
  - sbfl: sbfl-tarantula
    options:
      metric: tarantula
  - prob-graph
  - invariants
  - collect-bb: "sbfl-dstar collected"
    options:
      for: sbfl-dstar
  - irrelevant
