output_dir: bin

script:
  # Do all the stuff inside output directory
  - cd ${OUTPUT_DIR}
  # Analyse, instrument and compile sources
  - clang -Xclang -load -Xclang ${AARDWOLF_DIR}/libAardwolfLLVM.so -c -g -o maintenance.o ../src/*.c
  # Compile test runner and link it with the compiled source
  - clang -o run ../tests/test.c maintenance.o ${AARDWOLF_DIR}/libaardwolf_runtime.a
  # Execute the test runner
  - ./run > ${RESULT_FILE}

plugins:
  - sbfl: sbfl-dstar
    options:
      n_results: 20
  - sbfl: sbfl-ochai
    options:
      metric: ochiai
  - sbfl: sbfl-tarantula
    options:
      metric: tarantula
  - prob-graph
  - invariants
  - collect-bb: "sbfl-dstar collected"
    options:
      for: sbfl-dstar
  - irrelevant
