output_dir: .aardwolf

script:
  # Just run pytest (all the machinery is done in __init__.py and conftest.py)
  - pytest

plugins:
  - sbfl: D* Spectrum
  - prob-graph: Probabilistic Dependence
  - invariants: Likely Invariants
