output_dir: .aardwolf

script:
  # Just run pytest (all the machinery is done in test modules)
  - pytest

plugins:
  - sbfl: D* Spectrum
  - prob-graph: Probabilistic Dependence
  - invariants: Likely Invariants
