output_dir: bin

script:
  # Do all the stuff inside output directory
  - cd ${OUTPUT_DIR}
  # Analyse, instrument and compile sources
  - clang -Xclang -load -Xclang ${FRONTEND} -c -g -o ${TARGET_FILE}.o ../src/ppdg.c
  # Compile test runner and link it with the compiled source
  - clang -o ${EXEC_FILE} ../tests/ppdg.c ${TARGET_FILE}.o ${RUNTIME_LIB}
  # Execute the test runner
  - ${EXEC_FILE} > ${RESULT_FILE}
  # Temporary solution for limited static data collection
  - mv ppdg.c.aard ${ANALYSIS_FILE}

plugins:
  - prob-graph
