output_dir: bin

script:
  - cd ${OUTPUT_DIR}
  - rm -f *
  - clang -g -c -emit-llvm -o ${TARGET_FILE}.bc ../src/ppdg.c
  - ${FRONTEND} -d ${OUTPUT_DIR} ${TARGET_FILE}.bc
  - clang -g -o ${EXEC_FILE} ../tests/ppdg.c ${INSTR_FILE}.bc ${RUNTIME_LIB}
  - export AARDWOLF_DATA_DEST=${OUTPUT_DIR} && ${EXEC_FILE} > ${RESULT_FILE}
  - mv ${TARGET_FILE}.bc.aard ${ANALYSIS_FILE}

plugins:
  - prob-graph
