output_dir: bin

script:
  # Do all the stuff inside output directory
  - cd ${OUTPUT_DIR}
  # Analyse, instrument and compile sources
  - clang -Xclang -load -Xclang ${FRONTEND} -c -g -o ppdg.o ../src/ppdg.c
  # Compile test runner and link it with the compiled source
  - clang -o run ../tests/ppdg.c ppdg.o ${RUNTIME_LIB}
  # Execute the test runner
  - ./run > ${RESULT_FILE}

plugins:
  - prob-graph
